require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.5
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - bin/**/*
    - spec/dummy/bin/**/*
    - spec/dummy/db/migrate/*
    - spec/dummy/db/schema.rb


  DisplayCopNames: true


Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false


Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Layout/IndentFirstHashElement:
  EnforcedStyle: 'consistent'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Metrics/LineLength:
  Max: 128
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - classnames-rails-view.gemspec
    - spec/dummy/config/**/*
    - spec/dummy/Rakefile

Metrics/MethodLength:
  Max: 20

Naming/FileName:
  Exclude:
    - 'lib/classnames-rails-view.rb'