# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c29865b01a445e28fc097bb9dc9fbd31f5843bd219af93f4747898b6eb45960a6628c4b3a57b0631ec284b9c98dd2576e671986602bcb586767bd773c75cae24

test:
  secret_key_base: 78bab737cc919d17de4789f216fc16eb3abecf2693d51252a449f0bc737194ebc74e657066218ab3d83e45e29e2ad70726b99a5f47c1415aedfd6a8e2f32a39c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
